apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-agent-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/jenkins-agent-workspaces"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: jenkins-node
          operator: In
          values:
          - "true"
